import coreWebVitals from 'eslint-config-next/core-web-vitals'

/**
 * components/ui is generated by the shadcn/ui CLI and is upstream code we do
 * not hand-edit, so it is linted by its own project rather than this one.
 * Everything we author is covered.
 */
const config = [
  ...coreWebVitals,
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'server/node_modules/**',
      'docs/**',
      'components/ui/**',
    ],
  },
]

export default config
